name: Maven CI

on:
  #  push:
  #    branches:
  #      - main
  #      - testing-enviorment
  #    tags:
  #      - v*
  #  pull_request:
  #    branches:
  #      - main
  #      - testing-enviorment
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch or tag to run tests on'
        required: true
        default: 'main'
      environment:
        description: 'Deployment environment'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production
      buildParams:
        description: 'Build parameters in JSON format'
        required: true
        default: '{"teamId":"default-teamId", "signOption":"default-signOption", "appFilePath":"default-appFilePath", "keystoreFilePath":"default-keystoreFilePath", "certificateFilePath":"default-certificateFilePath", "fusionSetId":"default-fusionSetId", "signFingerprint":"default-signFingerprint", "entitlementsPath":"default1,default2", "mobileProvisionProfilesPath":"default1,default2", "buildToTest":"default-buildToTest", "buildWithLogs":"false", "googlePlaySign":"false", "secondOutput":"default-secondOutput"}'
      secretParams:
        description: 'Build parameters in JSON format'
        required: true
        default: '{"APPDOME_API_TOKEN":"default-APPDOME_API_TOKEN", "KEYSTORE_ALIAS":"default-KEYSTORE_ALIAS", "KEYSTORE_KEY_PASS":"default-KEYSTORE_KEY_PASS", "KEYSTORE_PASSWORD":"default-KEYSTORE_PASSWORD", "P12_PASSWORD":"default-P12_PASSWORD"}'
      logLevel:
        description: 'Set the log level for Maven builds'
        required: false
        default: 'info'
        type: choice
        options:
          - info
          - warning
          - debug
      dispatch_id:
        description: 'run_unique_id'
        required: true
        type: string

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Install jq
        run: sudo apt-get install jq

      - name: Download files from AWS S3 URLs
        id: download_files  # Assign an ID to the step to use outputs
        run: |
          # Extract parameters from JSON input
          buildParams='${{ github.event.inputs.buildParams }}'
          appFilePath=$(echo $buildParams | jq -r '.appFilePath')
          keystoreFilePath=$(echo $buildParams | jq -r '.keystoreFilePath')
          certificateFilePath=$(echo $buildParams | jq -r '.certificateFilePath')
          entitlementsPath=$(echo $buildParams | jq -r '.entitlementsPath')
          mobileProvisionProfilesPath=$(echo $buildParams | jq -r '.mobileProvisionProfilesPath')
          
          # Initialize local file paths
          localAppFilePath=""
          localKeystoreFilePath=""
          localCertificateFilePath=""
          localEntitlementsPaths=""
          localMobileProvisionPaths=""
          
          # Download files using curl and store them locally, only if they are not "None"
          if [ "$appFilePath" != "None" ]; then
              curl -o /tmp/app.apk "$appFilePath"
              echo "Downloaded app file to /tmp/app.apk"
              localAppFilePath="/tmp/app.apk"
          else
              echo "App file path is 'None', skipping download."
          fi
          
          if [ "$keystoreFilePath" != "None" ]; then
              curl -o /tmp/keystore.jks "$keystoreFilePath"
              echo "Downloaded keystore file to /tmp/keystore.jks"
              localKeystoreFilePath="/tmp/keystore.jks"
          else
              echo "Keystore file path is 'None', skipping download."
          fi
          
          if [ "$certificateFilePath" != "None" ]; then
              curl -o /tmp/certificate.pem "$certificateFilePath"
              echo "Downloaded certificate file to /tmp/certificate.pem"
              localCertificateFilePath="/tmp/certificate.pem"
          else
              echo "Certificate file path is 'None', skipping download."
          fi
          
          # Download entitlementsPath files, only if they are not "None"
          if [ "$entitlementsPath" != "None" ]; then
              IFS=',' read -ra entitlementUrls <<< "$entitlementsPath"
              for url in "${entitlementUrls[@]}"; do
                  fileName="/tmp/$(basename $url)"
                  curl -o "$fileName" "$url"
                  if [ -z "$localEntitlementsPaths" ]; then
                      localEntitlementsPaths="$fileName"
                  else
                      localEntitlementsPaths="$localEntitlementsPaths,$fileName"
                  fi
              done
              echo "Downloaded entitlement files: $localEntitlementsPaths"
          else
              echo "Entitlements path is 'None', skipping download."
          fi
          
          # Download mobileProvisionProfilesPath files, only if they are not "None"
          if [ "$mobileProvisionProfilesPath" != "None" ]; then
              IFS=',' read -ra provisionUrls <<< "$mobileProvisionProfilesPath"
              for url in "${provisionUrls[@]}"; do
                  fileName="/tmp/$(basename $url)"
                  curl -o "$fileName" "$url"
                  if [ -z "$localMobileProvisionPaths" ]; then
                      localMobileProvisionPaths="$fileName"
                  else
                      localMobileProvisionPaths="$localMobileProvisionPaths,$fileName"
                  fi
              done
              echo "Downloaded mobile provision profiles: $localMobileProvisionPaths"
          else
              echo "Mobile provision profiles path is 'None', skipping download."
          fi
          # Set outputs for next steps using Environment Files

          # Print and set each variable using Environment Files
          echo "appFilePath: $localAppFilePath"
            echo "appFilePath=$localAppFilePath" >> $GITHUB_ENV
          
          echo "keystoreFilePath: $localKeystoreFilePath"
            echo "keystoreFilePath=$localKeystoreFilePath" >> $GITHUB_ENV
          
          echo "certificateFilePath: $localCertificateFilePath"
            echo "certificateFilePath=$localCertificateFilePath" >> $GITHUB_ENV
          
          echo "entitlementsPath: $localEntitlementsPaths"
            echo "entitlementsPath=$localEntitlementsPaths" >> $GITHUB_ENV
          
          echo "mobileProvisionProfilesPath: $localMobileProvisionPaths"
            echo "mobileProvisionProfilesPath=$localMobileProvisionProfilesPath" >> $GITHUB_ENV
            


      - name: Build and Test with Maven
        run: |
          # Extract other parameters from JSON input
          buildParams='${{ github.event.inputs.buildParams }}'
          teamId=$(echo $buildParams | jq -r '.teamId')
          signOption=$(echo $buildParams | jq -r '.signOption')
          fusionSetId=$(echo $buildParams | jq -r '.fusionSetId')
          signFingerprint=$(echo $buildParams | jq -r '.signFingerprint')
          buildToTest=$(echo $buildParams | jq -r '.buildToTest')
          buildWithLogs=$(echo $buildParams | jq -r '.buildWithLogs')
          googlePlaySign=$(echo $buildParams | jq -r '.googlePlaySign')
          secondOutput=$(echo $buildParams | jq -r '.secondOutput')
          
          # Use outputs from the previous step for file paths
          appFilePath="${{ steps.download_files.outputs.appFilePath }}"
          keystoreFilePath="${{ steps.download_files.outputs.keystoreFilePath }}"
          certificateFilePath="${{ steps.download_files.outputs.certificateFilePath }}"
          entitlementsPath="${{ steps.download_files.outputs.entitlementsPath }}"
          mobileProvisionProfilesPath="${{ steps.download_files.outputs.mobileProvisionProfilesPath }}"
          
          # Echo each parameter to verify parsing worked correctly
          echo "Parsed Parameters:"
          echo "teamId: $teamId"
          echo "signOption: $signOption"
          echo "appFilePath: $appFilePath"
          echo "keystoreFilePath: $keystoreFilePath"
          echo "certificateFilePath: $certificateFilePath"
          echo "fusionSetId: $fusionSetId"
          echo "signFingerprint: $signFingerprint"
          echo "entitlementsPath: $entitlementsPath"
          echo "mobileProvisionProfilesPath: $mobileProvisionProfilesPath"
          echo "buildToTest: $buildToTest"
          echo "buildWithLogs: $buildWithLogs"
          echo "googlePlaySign: $googlePlaySign"
          echo "secondOutput: $secondOutput"
          
          # Run the Maven command with extracted parameters
          mvn -V --color always -ntp -B -Djenkins.test.timeout=700 -Dsurefire.printSummary=true -Dsurefire.useFile=false clean verify \
            -Dtest=PipelineTest#workFlowTest \
            -DteamId="$teamId" \
            -DsignOption="$signOption" \
            -DappFilePath="$appFilePath" \
            -DkeystoreFilePath="$keystoreFilePath" \
            -DcertificateFilePath="$certificateFilePath" \
            -DfusionSetId="$fusionSetId" \
            -DsignFingerprint="$signFingerprint" \
            -DentitlementsPath="$entitlementsPath" \
            -DmobileProvisionProfilesPath="$mobileProvisionProfilesPath" \
            -DbuildToTest="$buildToTest" \
            -DbuildWithLogs="$buildWithLogs" \
            -DgooglePlaySign="$googlePlaySign" \
            -DsecondOutput="$secondOutput" \
            -Denvironment="${{ github.event.inputs.environment }}" \
            package
        env:
          APPDOME_API_TOKEN: ${{ secrets.APPDOME_API_TOKEN }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEYSTORE_KEY_PASS: ${{ secrets.KEYSTORE_KEY_PASS }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
