name: Maven CI

on:
  push:
    branches:
      - main
      - testing-enviorment
    tags:
      - v*
  pull_request:
    branches:
      - main
      - testing-enviorment
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch or tag to run tests on'
        required: true
        default: 'main'
      environment:
        description: 'Deployment environment'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production
      teamId:
        description: 'Team ID for the plugin'
        required: true
        default: 'default-teamId'
      signOption:
        description: 'Signing option'
        required: true
        default: 'default-signOption'
      appFilePath:
        description: 'App file path'
        required: true
        default: 'default-appFilePath'
      keystoreFilePath:
        description: 'Keystore file path'
        required: true
        default: 'default-keystoreFilePath'
      certificateFilePath:
        description: 'Certificate file path'
        required: true
        default: 'default-certificateFilePath'
      fusionSetId:
        description: 'Fusion Set ID'
        required: true
        default: 'default-fusionSetId'
      signFingerprint:
        description: 'Sign Fingerprint'
        required: true
        default: 'default-signFingerprint'
      entitlementsPath:
        description: 'Entitlements path (comma-separated)'
        required: true
        default: 'default1,default2'
      mobileProvisionProfilesPath:
        description: 'Mobile provision profiles path (comma-separated)'
        required: true
        default: 'default1,default2'
      buildToTest:
        description: 'Build to test'
        required: true
        default: 'default-buildToTest'
      buildWithLogs:
        description: 'Build with logs (true/false)'
        required: true
        default: 'false'
      googlePlaySign:
        description: 'Google Play Signing (true/false)'
        required: true
        default: 'false'
      secondOutput:
        description: 'Second output'
        required: true
        default: 'default-secondOutput'
      logLevel:
        description: 'Set the log level for Maven builds'
        required: false
        default: 'info'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build and Test with Maven
        run: |
          mvn -V --color always -ntp -B -Djenkins.test.timeout=700 -Dsurefire.printSummary=true -Dsurefire.useFile=false clean verify \
            -Dtest=PipelineTest#workFlowTest \
            -DteamId='${{ github.event.inputs.teamId }}' \
            -DsignOption='${{ github.event.inputs.signOption }}' \
            -DappFilePath='${{ github.event.inputs.appFilePath }}' \
            -DkeystoreFilePath='${{ github.event.inputs.keystoreFilePath }}' \
            -DcertificateFilePath='${{ github.event.inputs.certificateFilePath }}' \
            -DfusionSetId='${{ github.event.inputs.fusionSetId }}' \
            -DsignFingerprint='${{ github.event.inputs.signFingerprint }}' \
            -DentitlementsPath='${{ github.event.inputs.entitlementsPath }}' \
            -DmobileProvisionProfilesPath='${{ github.event.inputs.mobileProvisionProfilesPath }}' \
            -DbuildToTest='${{ github.event.inputs.buildToTest }}' \
            -DbuildWithLogs='${{ github.event.inputs.buildWithLogs }}' \
            -DgooglePlaySign='${{ github.event.inputs.googlePlaySign }}' \
            -DsecondOutput='${{ github.event.inputs.secondOutput }}' \
            -Denvironment='${{ github.event.inputs.environment }}' \
            package
