name: Maven CI

on:
  push:
    branches:
      - main
      - testing-enviorment
    tags:
      - v*
  pull_request:
    branches:
      - main
      - testing-enviorment
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch or tag to run tests on'
        required: true
        default: 'main'
      environment:
        description: 'Deployment environment'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production
      buildParams:
        description: 'Build parameters in JSON format'
        required: true
        default: '{"teamId":"default-teamId", "signOption":"default-signOption", "appFilePath":"default-appFilePath", "keystoreFilePath":"default-keystoreFilePath", "certificateFilePath":"default-certificateFilePath", "fusionSetId":"default-fusionSetId", "signFingerprint":"default-signFingerprint", "entitlementsPath":"default1,default2", "mobileProvisionProfilesPath":"default1,default2", "buildToTest":"default-buildToTest", "buildWithLogs":"false", "googlePlaySign":"false", "secondOutput":"default-secondOutput"}'
      logLevel:
        description: 'Set the log level for Maven builds'
        required: false
        default: 'info'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Install jq
        run: sudo apt-get install jq

      - name: Download files from AWS S3 URLs
        run: |
          # Extract parameters from JSON input
          buildParams='${{ github.event.inputs.buildParams }}'
          appFilePath=$(echo $buildParams | jq -r '.appFilePath')
          keystoreFilePath=$(echo $buildParams | jq -r '.keystoreFilePath')
          certificateFilePath=$(echo $buildParams | jq -r '.certificateFilePath')
          entitlementsPath=$(echo $buildParams | jq -r '.entitlementsPath')
          mobileProvisionProfilesPath=$(echo $buildParams | jq -r '.mobileProvisionProfilesPath')

          # Download files using curl and store them locally
          curl -o /tmp/app.apk "$appFilePath"
          curl -o /tmp/keystore.jks "$keystoreFilePath"
          [ "$certificateFilePath" != "None" ] && curl -o /tmp/certificate.pem "$certificateFilePath" || echo "Certificate file path is 'None', skipping download."

          # Download entitlementsPath files
          localEntitlementsPaths=""
          IFS=',' read -ra entitlementUrls <<< "$entitlementsPath"
          for url in "${entitlementUrls[@]}"; do
              fileName="/tmp/$(basename $url)"
              curl -o "$fileName" "$url"
              if [ -z "$localEntitlementsPaths" ]; then
                  localEntitlementsPaths="$fileName"
              else
                  localEntitlementsPaths="$localEntitlementsPaths,$fileName"
              fi
          done

          # Download mobileProvisionProfilesPath files
          localMobileProvisionPaths=""
          IFS=',' read -ra provisionUrls <<< "$mobileProvisionProfilesPath"
          for url in "${provisionUrls[@]}"; do
              fileName="/tmp/$(basename $url)"
              curl -o "$fileName" "$url"
              if [ -z "$localMobileProvisionPaths" ]; then
                  localMobileProvisionPaths="$fileName"
              else
                  localMobileProvisionPaths="$localMobileProvisionPaths,$fileName"
              fi
          done

          # Update the paths to use local paths
          appFilePath="/tmp/app.apk"
          keystoreFilePath="/tmp/keystore.jks"
          certificateFilePath="/tmp/certificate.pem"

          # Output local paths to be used later
          echo "Local app file path: $appFilePath"
          echo "Local keystore file path: $keystoreFilePath"
          echo "Local certificate file path: $certificateFilePath"
          echo "Local entitlements paths: $localEntitlementsPaths"
          echo "Local mobile provision profiles paths: $localMobileProvisionPaths"


      - name: Build and Test with Maven
        run: |
          # Extract other parameters from JSON input
          teamId=$(echo '${{ github.event.inputs.buildParams }}' | jq -r '.teamId')
          signOption=$(echo '${{ github.event.inputs.buildParams }}' | jq -r '.signOption')
          fusionSetId=$(echo '${{ github.event.inputs.buildParams }}' | jq -r '.fusionSetId')
          signFingerprint=$(echo '${{ github.event.inputs.buildParams }}' | jq -r '.signFingerprint')
          buildToTest=$(echo '${{ github.event.inputs.buildParams }}' | jq -r '.buildToTest')
          buildWithLogs=$(echo '${{ github.event.inputs.buildParams }}' | jq -r '.buildWithLogs')
          googlePlaySign=$(echo '${{ github.event.inputs.buildParams }}' | jq -r '.googlePlaySign')
          secondOutput=$(echo '${{ github.event.inputs.buildParams }}' | jq -r '.secondOutput')
          
          # Echo each parameter to verify parsing worked correctly
          echo "Parsed Parameters:"
          echo "teamId: $teamId"
          echo "signOption: $signOption"
          echo "appFilePath: $appFilePath"
          echo "keystoreFilePath: $keystoreFilePath"
          echo "certificateFilePath: $certificateFilePath"
          echo "fusionSetId: $fusionSetId"
          echo "signFingerprint: $signFingerprint"
          echo "entitlementsPath: $localEntitlementsPaths"
          echo "mobileProvisionProfilesPath: $localMobileProvisionPaths"
          echo "buildToTest: $buildToTest"
          echo "buildWithLogs: $buildWithLogs"
          echo "googlePlaySign: $googlePlaySign"
          echo "secondOutput: $secondOutput"
          
          # Run the Maven command with extracted parameters
          mvn -V --color always -ntp -B -Djenkins.test.timeout=700 -Dsurefire.printSummary=true -Dsurefire.useFile=false clean verify \
            -Dtest=PipelineTest#workFlowTest \
            -DteamId="$teamId" \
            -DsignOption="$signOption" \
            -DappFilePath="$appFilePath" \
            -DkeystoreFilePath="$keystoreFilePath" \
            -DcertificateFilePath="$certificateFilePath" \
            -DfusionSetId="$fusionSetId" \
            -DsignFingerprint="$signFingerprint" \
            -DentitlementsPath="$localEntitlementsPaths" \
            -DmobileProvisionProfilesPath="$localMobileProvisionPaths" \
            -DbuildToTest="$buildToTest" \
            -DbuildWithLogs="$buildWithLogs" \
            -DgooglePlaySign="$googlePlaySign" \
            -DsecondOutput="$secondOutput" \
            -Denvironment="${{ github.event.inputs.environment }}" \
            package
